[features]
seeds = false
skip-lint = false
[programs.localnet]
token_contract = "8skxgJuuJicPJFqT4oS1hLfDpdyBXQhi7Q5zP6hK71gt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/falcon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
